/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppId = IDL.Text;
export const AppCategory = IDL.Variant({
  'tools' : IDL.Null,
  'social' : IDL.Null,
  'entertainment' : IDL.Null,
  'productivity' : IDL.Null,
  'education' : IDL.Null,
  'games' : IDL.Null,
});
export const Time = IDL.Int;
export const Review = IDL.Record({
  'comment' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Principal,
});
export const App = IDL.Record({
  'id' : AppId,
  'reviews' : IDL.Vec(Review),
  'name' : IDL.Text,
  'numReviews' : IDL.Nat,
  'description' : IDL.Text,
  'fileSize' : IDL.Nat,
  'version' : IDL.Text,
  'screenshots' : IDL.Vec(IDL.Text),
  'category' : AppCategory,
  'downloadCount' : IDL.Nat,
  'rating' : IDL.Nat,
  'iconUrl' : IDL.Text,
  'releaseDate' : Time,
  'developer' : IDL.Text,
});

export const idlService = IDL.Service({
  'addApp' : IDL.Func(
      [
        AppId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        AppCategory,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        Time,
      ],
      [],
      [],
    ),
  'addReview' : IDL.Func([AppId, IDL.Nat, IDL.Text], [], []),
  'getAllApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
  'getAppById' : IDL.Func([AppId], [IDL.Opt(App)], ['query']),
  'getAppsByCategory' : IDL.Func([AppCategory], [IDL.Vec(App)], ['query']),
  'searchAppsByDeveloper' : IDL.Func([IDL.Text], [IDL.Vec(App)], ['query']),
  'searchAppsByName' : IDL.Func([IDL.Text], [IDL.Vec(App)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppId = IDL.Text;
  const AppCategory = IDL.Variant({
    'tools' : IDL.Null,
    'social' : IDL.Null,
    'entertainment' : IDL.Null,
    'productivity' : IDL.Null,
    'education' : IDL.Null,
    'games' : IDL.Null,
  });
  const Time = IDL.Int;
  const Review = IDL.Record({
    'comment' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Principal,
  });
  const App = IDL.Record({
    'id' : AppId,
    'reviews' : IDL.Vec(Review),
    'name' : IDL.Text,
    'numReviews' : IDL.Nat,
    'description' : IDL.Text,
    'fileSize' : IDL.Nat,
    'version' : IDL.Text,
    'screenshots' : IDL.Vec(IDL.Text),
    'category' : AppCategory,
    'downloadCount' : IDL.Nat,
    'rating' : IDL.Nat,
    'iconUrl' : IDL.Text,
    'releaseDate' : Time,
    'developer' : IDL.Text,
  });
  
  return IDL.Service({
    'addApp' : IDL.Func(
        [
          AppId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AppCategory,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          Time,
        ],
        [],
        [],
      ),
    'addReview' : IDL.Func([AppId, IDL.Nat, IDL.Text], [], []),
    'getAllApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
    'getAppById' : IDL.Func([AppId], [IDL.Opt(App)], ['query']),
    'getAppsByCategory' : IDL.Func([AppCategory], [IDL.Vec(App)], ['query']),
    'searchAppsByDeveloper' : IDL.Func([IDL.Text], [IDL.Vec(App)], ['query']),
    'searchAppsByName' : IDL.Func([IDL.Text], [IDL.Vec(App)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };