/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface App {
  'id' : AppId,
  'reviews' : Array<Review>,
  'name' : string,
  'numReviews' : bigint,
  'description' : string,
  'fileSize' : bigint,
  'version' : string,
  'screenshots' : Array<string>,
  'category' : AppCategory,
  'downloadCount' : bigint,
  'rating' : bigint,
  'iconUrl' : string,
  'releaseDate' : Time,
  'developer' : string,
}
export type AppCategory = { 'tools' : null } |
  { 'social' : null } |
  { 'entertainment' : null } |
  { 'productivity' : null } |
  { 'education' : null } |
  { 'games' : null };
export type AppId = string;
export interface Review {
  'comment' : string,
  'timestamp' : Time,
  'rating' : bigint,
  'reviewer' : Principal,
}
export type Time = bigint;
export interface _SERVICE {
  'addApp' : ActorMethod<
    [
      AppId,
      string,
      string,
      string,
      AppCategory,
      string,
      bigint,
      string,
      Array<string>,
      Time,
    ],
    undefined
  >,
  'addReview' : ActorMethod<[AppId, bigint, string], undefined>,
  'getAllApps' : ActorMethod<[], Array<App>>,
  'getAppById' : ActorMethod<[AppId], [] | [App]>,
  'getAppsByCategory' : ActorMethod<[AppCategory], Array<App>>,
  'searchAppsByDeveloper' : ActorMethod<[string], Array<App>>,
  'searchAppsByName' : ActorMethod<[string], Array<App>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];