/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type AppId = string;
export interface App {
    id: AppId;
    reviews: Array<Review>;
    name: string;
    numReviews: bigint;
    description: string;
    fileSize: bigint;
    version: string;
    screenshots: Array<string>;
    category: AppCategory;
    downloadCount: bigint;
    rating: bigint;
    iconUrl: string;
    releaseDate: Time;
    developer: string;
}
export type Time = bigint;
export interface Review {
    comment: string;
    timestamp: Time;
    rating: bigint;
    reviewer: Principal;
}
export enum AppCategory {
    tools = "tools",
    social = "social",
    entertainment = "entertainment",
    productivity = "productivity",
    education = "education",
    games = "games"
}
export interface backendInterface {
    addApp(id: AppId, name: string, description: string, developer: string, category: AppCategory, version: string, fileSize: bigint, iconUrl: string, screenshots: Array<string>, releaseDate: Time): Promise<void>;
    addReview(appId: AppId, rating: bigint, comment: string): Promise<void>;
    getAllApps(): Promise<Array<App>>;
    getAppById(id: AppId): Promise<App | null>;
    getAppsByCategory(category: AppCategory): Promise<Array<App>>;
    searchAppsByDeveloper(searchTerm: string): Promise<Array<App>>;
    searchAppsByName(searchTerm: string): Promise<Array<App>>;
}
import type { App as _App, AppCategory as _AppCategory, AppId as _AppId, Review as _Review, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addApp(arg0: AppId, arg1: string, arg2: string, arg3: string, arg4: AppCategory, arg5: string, arg6: bigint, arg7: string, arg8: Array<string>, arg9: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addApp(arg0, arg1, arg2, arg3, to_candid_AppCategory_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addApp(arg0, arg1, arg2, arg3, to_candid_AppCategory_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async addReview(arg0: AppId, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllApps(): Promise<Array<App>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApps();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApps();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppById(arg0: AppId): Promise<App | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppById(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppById(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppsByCategory(arg0: AppCategory): Promise<Array<App>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppsByCategory(to_candid_AppCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppsByCategory(to_candid_AppCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchAppsByDeveloper(arg0: string): Promise<Array<App>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAppsByDeveloper(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAppsByDeveloper(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchAppsByName(arg0: string): Promise<Array<App>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAppsByName(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAppsByName(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppCategory): AppCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_App_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _App): App {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_App]): App | null {
    return value.length === 0 ? null : from_candid_App_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AppId;
    reviews: Array<_Review>;
    name: string;
    numReviews: bigint;
    description: string;
    fileSize: bigint;
    version: string;
    screenshots: Array<string>;
    category: _AppCategory;
    downloadCount: bigint;
    rating: bigint;
    iconUrl: string;
    releaseDate: _Time;
    developer: string;
}): {
    id: AppId;
    reviews: Array<Review>;
    name: string;
    numReviews: bigint;
    description: string;
    fileSize: bigint;
    version: string;
    screenshots: Array<string>;
    category: AppCategory;
    downloadCount: bigint;
    rating: bigint;
    iconUrl: string;
    releaseDate: Time;
    developer: string;
} {
    return {
        id: value.id,
        reviews: value.reviews,
        name: value.name,
        numReviews: value.numReviews,
        description: value.description,
        fileSize: value.fileSize,
        version: value.version,
        screenshots: value.screenshots,
        category: from_candid_AppCategory_n6(_uploadFile, _downloadFile, value.category),
        downloadCount: value.downloadCount,
        rating: value.rating,
        iconUrl: value.iconUrl,
        releaseDate: value.releaseDate,
        developer: value.developer
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tools: null;
} | {
    social: null;
} | {
    entertainment: null;
} | {
    productivity: null;
} | {
    education: null;
} | {
    games: null;
}): AppCategory {
    return "tools" in value ? AppCategory.tools : "social" in value ? AppCategory.social : "entertainment" in value ? AppCategory.entertainment : "productivity" in value ? AppCategory.productivity : "education" in value ? AppCategory.education : "games" in value ? AppCategory.games : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_App>): Array<App> {
    return value.map((x)=>from_candid_App_n4(_uploadFile, _downloadFile, x));
}
function to_candid_AppCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppCategory): _AppCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppCategory): {
    tools: null;
} | {
    social: null;
} | {
    entertainment: null;
} | {
    productivity: null;
} | {
    education: null;
} | {
    games: null;
} {
    return value == AppCategory.tools ? {
        tools: null
    } : value == AppCategory.social ? {
        social: null
    } : value == AppCategory.entertainment ? {
        entertainment: null
    } : value == AppCategory.productivity ? {
        productivity: null
    } : value == AppCategory.education ? {
        education: null
    } : value == AppCategory.games ? {
        games: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
